- src/apis/Animated/index.js
- src/components/Touchable/TouchableBounce.js
- src/components/Touchable/TouchableOpacity.js
- src/index.js
Both `TouchableBounce` and `TouchableOpacity` broke because they expect `Animated.View` to exist on the animated module. I added back `src/apis/Animated/index.js` so it's initialized in a single place.
> Add an API to wrap and initialize animated

- docs/apis/StyleSheet.md
**This patch solves the following problem**
Fix a broken internal link and a typo in the StyleSheet API docs page.
**Test plan**
Go to [docs/api/StyleSheet.md](https://github.com/vitorbal/react-native-web/blob/patch-1/docs/apis/StyleSheet.md), click the link in the first paragraph that says "how to style your application". The link should now work whereas it didn't before.
**This pull request**
> Fix broken link and typo in StyleSheet API docs

- src/components/ListView/index.js
**This patch solves the following problem**
The current ListView implementation (v0.0.45) fails to proxy the relevant calls to its contained ScrollView, this seems due to two things:
- the `_setScrollViewRef()` function is not bound to the class, so `this` points to `window` rather than the ListView instance
- no props are passed to the ScrollView, the arguments provided to [Lodash's `pick()`](https://lodash.com/docs/4.15.0#pick) do not match the expected signature
This PR addresses these two issues.
**Test plan**
No existing test for ListView to update, so only local test usage
**This pull request**
> ListView fixes for contained ScrollView

- docs/components/View.md
- src/components/View/ViewStylePropTypes.js
**This patch solves the following problem**
It allows the `filter` CSS rule.
> Allow filter property in CSS

- docs/storybook/1-components/Touchable/TouchableHighlightDocs.js
- docs/storybook/1-components/Touchable/TouchableOpacityDocs.js
- docs/storybook/1-components/Touchable/TouchableWithoutFeedbackDocs.js
- docs/storybook/1-components/Touchable/examples/DelayEvents.js
- docs/storybook/1-components/Touchable/examples/FeedbackEvents.js
- docs/storybook/1-components/Touchable/examples/PropDisabled.js
- docs/storybook/1-components/Touchable/examples/legacy.js
- src/components/TextInput/index.js
- src/components/Touchable/Touchable.js
- src/components/Touchable/TouchableHighlight.js
- src/components/Touchable/TouchableNativeFeedback.js
- src/components/Touchable/TouchableOpacity.js
- src/components/Touchable/TouchableWithoutFeedback.js
**Problem**
Although 'Touchable' supports basic keyboard usage, it doesn't support
delays or interaction via the Space key.
**Solution**
Extend the 'Touchable' mixin to better support keyboard interactions.
All touchable callbacks and delays are now supported when interacted
with via a keyboard's Enter and Space keys (as would be expected of
native 'button' elements). However, events are not normalized to mimic
touch events.
Minor upstream changes to the Touchables in React Native are also
included.
> [change] better Touchable support for keyboards

- src/modules/createElement/__tests__/__snapshots__/index-test.js.snap
- src/modules/createElement/__tests__/index-test.js
- src/modules/normalizeNativeEvent/__tests__/__snapshots__/index-test.js.snap
- src/modules/normalizeNativeEvent/__tests__/index-test.js
- src/modules/normalizeNativeEvent/index.js
Work better with simulated events, and avoid crashing if
'nativeEvent.target' isn't an element node.
Close #597
> [fix] event normalization

- src/apis/AppRegistry/renderApplication.js
I think, version v0.2.0 is broken due to named import of default export
> [fix] corrupt hydrate import breaking v0.2.0

- packages/react-native-web/src/exports/AppRegistry/__tests__/index-test.js
- packages/react-native-web/src/exports/AppRegistry/renderApplication.js
- packages/react-native-web/src/exports/StyleSheet/StyleSheetManager.js
- packages/react-native-web/src/exports/StyleSheet/WebStyleSheet.js
- packages/react-native-web/src/exports/StyleSheet/index.js
- packages/react-native-web/src/exports/StyleSheet/modality.js
- packages/react-native-web/src/modules/applyLayout/index.js
- website/storybook/2-apis/AppRegistry/AppRegistryScreen.js
onLayout is called after the component is mounted to the DOM. This makes
both the fallback and ResizeObserver code path behave the same as React
Native.
Fix #911
Fix #941
Close #939
> [fix] onLayout timing without ResizeObserver 

- packages/react-native-web/src/exports/StyleSheet/__tests__/createReactDOMStyle-test.js
- packages/react-native-web/src/exports/StyleSheet/createReactDOMStyle.js
Remove the deprecated 'transformMatrix' style prop and support 'matrix' and
'matrix3d' in the 'transform' prop.
Fix #1771
> [fix] Add matrix transform style

- packages/react-native-web/src/exports/Button/__tests__/__snapshots__/index-test.js.snap
- packages/react-native-web/src/exports/Image/__tests__/__snapshots__/index-test.js.snap
- packages/react-native-web/src/exports/Image/__tests__/index-test.js
- packages/react-native-web/src/exports/Pressable/__tests__/__snapshots__/index-test.js.snap
- packages/react-native-web/src/exports/createElement/__tests__/index-test.js
- packages/react-native-web/src/modules/createDOMProps/__tests__/index-test.js
- packages/react-native-web/src/modules/createDOMProps/index.js
> [fix] Allow focusable={false} to set tabIndex="-1"

- package-lock.json
- packages/react-native-web-examples/pages/pressable/index.js
- packages/react-native-web/src/exports/Pressable/__tests__/index-test.js
- packages/react-native-web/src/exports/Pressable/index.js
> [fix] Allow Pressable to be programmatically focused when disabled

- package-lock.json
- packages/react-native-web/package.json
- packages/react-native-web/src/exports/Image/__tests__/__snapshots__/index-test.js.snap
- packages/react-native-web/src/exports/Image/__tests__/index-test.js
- packages/react-native-web/src/exports/Image/index.js
- packages/react-native-web/src/exports/Image/types.js
- packages/react-native-web/src/exports/StyleSheet/index.js
- packages/react-native-web/src/exports/StyleSheet/preprocess.js
- packages/react-native-web/src/modules/createDOMProps/index.js
- packages/react-native-web/src/types/styles.js
Cannot pass the result of StyleSheet.flatten to components, as it mixes dynamic and static (compiled away) style information.
With the way Image is currently implemented, we have to override 'boxShadow' in all cases to avoid the 'shadow*' props being incorrectly applied as a box-shadow. Once Image is implemented using createElement, we can disable the 'boxShadow" generation just for Image.
Fix #2527
> [fix] Image: style resolving

- packages/react-native-web/src/exports/Pressable/__tests__/index-test.js
- packages/react-native-web/src/modules/usePressEvents/PressResponder.js
Update keyboard handling code to avoid calling preventDefault for 'keydown' events occuring on a native button element. This was causing native 'click' event to be cancelled on buttons.
Fix #2560
> [fix] Pressable button click regression

- packages/react-native-web-docs/src/pages/docs/getting-started/help.md
- packages/react-native-web-docs/src/pages/docs/getting-started/typescript-support.md
This PR is a follow-up to [this one](https://github.com/necolas/react-native-web/pull/2702). [As we decided to add RNW types to DefinitelyTyped repo](https://github.com/necolas/react-native-web/issues/1684#issuecomment-2274296791), we are now just adding instructions to the documentation explaining how to use them.
> Add TypeScript support page

- packages/react-native-web/src/exports/TextInput/index.js
Check if the input is still focused before selecting text
Fix #2704
> [fix] TextInput refocusing issue with selectTextOnFocus

- packages/react-native-web/src/modules/useLocale/isLocaleRTL.js
React native web throws a hard error if the locale is invalid.
This is one of the most common errors according to our error logging.
This hard error seems unnecessary, so try catch and just assume ltr if not supported locale
> [fix] dont throw if invalid locale

- packages/react-native-web-docs/src/pages/docs/concepts/accessibility.md
- packages/react-native-web/src/exports/Button/index.js
- packages/react-native-web/src/exports/StyleSheet/index.js
- packages/react-native-web/src/exports/StyleSheet/preprocess.js
- packages/react-native-web/src/exports/Text/index.js
- packages/react-native-web/src/exports/TextInput/index.js
- packages/react-native-web/src/exports/TouchableHighlight/index.js
- packages/react-native-web/src/exports/TouchableOpacity/index.js
- packages/react-native-web/src/modules/createDOMProps/index.js
Removes warnings for non-standard APIs in React Native, given there has been no upstream interest in deprecating them. And the standards-based approach to cross-platform React is instead being built into React Strict DOM.
cc @EvanBacon for Expo approval
> Remove API deprecation warnings

- packages/react-native-web/src/exports/StyleSheet/__tests__/preprocess-test.js
- packages/react-native-web/src/exports/StyleSheet/preprocess.js
Related to https://github.com/necolas/react-native-web/issues/2752
> [feat] Support style boxShadow as array

- packages/react-native-web/src/exports/StyleSheet/__tests__/preprocess-test.js
- packages/react-native-web/src/exports/StyleSheet/preprocess.js
- packages/react-native-web/src/types/styles.js
> **Array syntax**
> `transformOrigin` also supports an array syntax. It makes it convenient to use it with Animated APIs. It also avoids string parsing, so should be more efficient.
[React Native documentation](https://reactnative.dev/docs/transforms#array-syntax)
> [fix] Support array syntax on transformOrigin

- packages/react-native-web/src/vendor/react-native/Animated/nodes/AnimatedProps.js
While working with `@react-navigation` package I noticed a leak that was leaving multiple `Detached <div>` instances in the memory while using `Animated API` on web. They were never garbage collected.
After a [week-long investigation](https://github.com/react-navigation/react-navigation/issues/12702) I finally found the root cause for the problem. It turned out that `_animatedView` instance was never set to `null`, even after detaching the element. It turned out that this problem [has already been solved](https://github.com/facebook/react-native/blob/ce8fe490db7556421736bdaf8c01dba98fb53e36/packages/react-native/Libraries/Animated/nodes/AnimatedProps.js#L170) in the `react-native` repository. But since `react-native-web` uses an older version of React Native it was not reflected in the …
> Fix memory leak with Animated API
